name: iosApp
options:
  bundleIdPrefix: com.edugo
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  base:
    ENABLE_USER_SCRIPT_SANDBOXING: "NO"

configFiles:
  Debug: Configuration/Config.xcconfig
  Release: Configuration/Config.xcconfig

targets:
  iosApp:
    type: application
    platform: iOS
    sources:
      - path: iosApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.edugo.app.ios
        INFOPLIST_FILE: iosApp/Info.plist
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1,2"
    preBuildScripts:
      - name: "Compile Kotlin Framework"
        script: |
          cd "$SRCROOT/.."
          ./gradlew :platforms:mobile:app:embedAndSignAppleFrameworkForXcode
        basedOnDependencyAnalysis: false
